name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: ./src/iOS/HealthSense
    - uses: actions/checkout@master
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
# working-directory: ./src/iOS/HealthSense
