name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: ./src/iOS/HealthSense

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd $PWD && ls
    - name: Build2
      run: cd src/iOS/HealthSense &&  ls
      working-directory: ./src/iOS/HealthSense
    - name: Build3
      run: xcodebuild -list -project  HealthSense.xcodeproj
    - name: Build4
      run: xcodebuild -list
    - name: Build6
      run: xcodebuild -scheme HealthSense -project HealthSense.xcodeproj/ build -allowProvisioningUpdates 
    - name: Build5
      run: xcodebuild -scheme HealthSense -project HealthSense.xcodeproj/ -allowProvisioningUpdates  build
   
    - name: Run tests
      run: swift test -v
# working-directory: ./src/iOS/HealthSense
